"""initial schema

Revision ID: ca46685ffeeb
Revises:
Create Date: 2026-09-13 02:11:15.732931
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ca46685ffeeb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("target_type", sa.String(length=60), nullable=True),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_index("ix_audit_tenant_time", "audit_logs", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "firmware_email_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("vendor", sa.String(length=50), nullable=False),
        sa.Column("model_pattern", sa.String(length=200), nullable=True),
        sa.Column("firmware_pattern", sa.String(length=200), nullable=True),
        sa.Column(
            "field_regexes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "event_label_map",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("media_retention_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_armed", sa.Boolean(), nullable=False),
        sa.Column("is_offline", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sites_tenant_id"), "sites", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("vendor", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("firmware_version", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("channel_count", sa.Integer(), nullable=True),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("email_profile_id", sa.UUID(), nullable=True),
        sa.Column("commissioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_profile_id"], ["firmware_email_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_site_id"), "devices", ["site_id"], unique=False)
    op.create_index(op.f("ix_devices_tenant_id"), "devices", ["tenant_id"], unique=False)
    op.create_table(
        "push_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=10), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_push_devices_token"),
    )
    op.create_index(op.f("ix_push_devices_tenant_id"), "push_devices", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_push_devices_user_id"), "push_devices", ["user_id"], unique=False)
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "event_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "camera_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "zone_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "schedule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("min_ai_confidence", sa.Float(), nullable=False),
        sa.Column("min_severity", sa.String(length=10), nullable=False),
        sa.Column(
            "actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("if_ai_unavailable", sa.String(length=30), nullable=False),
        sa.Column(
            "weights",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rules_site_id"), "rules", ["site_id"], unique=False)
    op.create_index(op.f("ix_rules_tenant_id"), "rules", ["tenant_id"], unique=False)
    op.create_table(
        "cameras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("channel_number", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("has_perimeter_rule", sa.Boolean(), nullable=False),
        sa.Column("last_snapshot_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "channel_number", name="uq_camera_device_channel"),
    )
    op.create_index(op.f("ix_cameras_device_id"), "cameras", ["device_id"], unique=False)
    op.create_index(op.f("ix_cameras_site_id"), "cameras", ["site_id"], unique=False)
    op.create_index(op.f("ix_cameras_tenant_id"), "cameras", ["tenant_id"], unique=False)
    op.create_table(
        "device_silence_state",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("state_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_index(
        op.f("ix_device_silence_state_tenant_id"),
        "device_silence_state",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "device_smtp_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="uq_smtp_username"),
    )
    op.create_index(
        op.f("ix_device_smtp_accounts_device_id"),
        "device_smtp_accounts",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_smtp_accounts_tenant_id"),
        "device_smtp_accounts",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "email_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("source_message_id", sa.String(length=400), nullable=False),
        sa.Column("smtp_auth_user", sa.String(length=120), nullable=False),
        sa.Column("sender_ip", sa.String(length=45), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("parse_status", sa.String(length=20), nullable=False),
        sa.Column("profile_name", sa.String(length=120), nullable=True),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_message_id", name="uq_email_message_id"),
    )
    op.create_index(
        "ix_email_messages_device_time",
        "email_messages",
        ["device_id", "received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_tenant_id"), "email_messages", ["tenant_id"], unique=False
    )
    op.create_table(
        "email_samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("firmware_version", sa.String(length=100), nullable=True),
        sa.Column("profile_name", sa.String(length=120), nullable=True),
        sa.Column("raw_message", sa.LargeBinary(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_samples_device_id"), "email_samples", ["device_id"], unique=False
    )
    op.create_table(
        "camera_zones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("zone_type", sa.String(length=30), nullable=False),
        sa.Column(
            "points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_camera_zones_camera_id"), "camera_zones", ["camera_id"], unique=False)
    op.create_index(op.f("ix_camera_zones_tenant_id"), "camera_zones", ["tenant_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("vendor_label", sa.String(length=200), nullable=True),
        sa.Column("channel_number", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at_local", sa.DateTime(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_message_id", sa.String(length=400), nullable=True),
        sa.Column("dedup_key", sa.String(length=300), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column(
            "risk_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("parse_status", sa.String(length=20), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint("risk_score >= 0 AND risk_score <= 100", name="ck_events_risk_range"),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_camera_id"), "events", ["camera_id"], unique=False)
    op.create_index("ix_events_dedup", "events", ["dedup_key", "occurred_at"], unique=False)
    op.create_index(op.f("ix_events_device_id"), "events", ["device_id"], unique=False)
    op.create_index(op.f("ix_events_site_id"), "events", ["site_id"], unique=False)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index("ix_events_tenant_time", "events", ["tenant_id", "occurred_at"], unique=False)
    op.create_table(
        "alarms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolution_code", sa.String(length=40), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("escalation_step", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["rules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alarms_event_id"), "alarms", ["event_id"], unique=False)
    op.create_index(op.f("ix_alarms_site_id"), "alarms", ["site_id"], unique=False)
    op.create_index(op.f("ix_alarms_tenant_id"), "alarms", ["tenant_id"], unique=False)
    op.create_index("ix_alarms_tenant_status", "alarms", ["tenant_id", "status"], unique=False)
    op.create_table(
        "event_detections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "box",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column(
            "zone_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_detections_event_id"), "event_detections", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_detections_tenant_id"), "event_detections", ["tenant_id"], unique=False
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key", name="uq_media_storage_key"),
    )
    op.create_index(op.f("ix_media_assets_event_id"), "media_assets", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_media_assets_expires_at"), "media_assets", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_media_assets_tenant_id"), "media_assets", ["tenant_id"], unique=False)
    op.create_table(
        "alarm_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("alarm_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("escalation_step", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alarm_id"], ["alarms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alarm_deliveries_alarm_id"), "alarm_deliveries", ["alarm_id"], unique=False
    )
    op.create_index(
        op.f("ix_alarm_deliveries_tenant_id"), "alarm_deliveries", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alarm_deliveries_tenant_id"), table_name="alarm_deliveries")
    op.drop_index(op.f("ix_alarm_deliveries_alarm_id"), table_name="alarm_deliveries")
    op.drop_table("alarm_deliveries")
    op.drop_index(op.f("ix_media_assets_tenant_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_expires_at"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_event_id"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_event_detections_tenant_id"), table_name="event_detections")
    op.drop_index(op.f("ix_event_detections_event_id"), table_name="event_detections")
    op.drop_table("event_detections")
    op.drop_index("ix_alarms_tenant_status", table_name="alarms")
    op.drop_index(op.f("ix_alarms_tenant_id"), table_name="alarms")
    op.drop_index(op.f("ix_alarms_site_id"), table_name="alarms")
    op.drop_index(op.f("ix_alarms_event_id"), table_name="alarms")
    op.drop_table("alarms")
    op.drop_index("ix_events_tenant_time", table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index(op.f("ix_events_site_id"), table_name="events")
    op.drop_index(op.f("ix_events_device_id"), table_name="events")
    op.drop_index("ix_events_dedup", table_name="events")
    op.drop_index(op.f("ix_events_camera_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_camera_zones_tenant_id"), table_name="camera_zones")
    op.drop_index(op.f("ix_camera_zones_camera_id"), table_name="camera_zones")
    op.drop_table("camera_zones")
    op.drop_index(op.f("ix_email_samples_device_id"), table_name="email_samples")
    op.drop_table("email_samples")
    op.drop_index(op.f("ix_email_messages_tenant_id"), table_name="email_messages")
    op.drop_index("ix_email_messages_device_time", table_name="email_messages")
    op.drop_table("email_messages")
    op.drop_index(op.f("ix_device_smtp_accounts_tenant_id"), table_name="device_smtp_accounts")
    op.drop_index(op.f("ix_device_smtp_accounts_device_id"), table_name="device_smtp_accounts")
    op.drop_table("device_smtp_accounts")
    op.drop_index(op.f("ix_device_silence_state_tenant_id"), table_name="device_silence_state")
    op.drop_table("device_silence_state")
    op.drop_index(op.f("ix_cameras_tenant_id"), table_name="cameras")
    op.drop_index(op.f("ix_cameras_site_id"), table_name="cameras")
    op.drop_index(op.f("ix_cameras_device_id"), table_name="cameras")
    op.drop_table("cameras")
    op.drop_index(op.f("ix_rules_tenant_id"), table_name="rules")
    op.drop_index(op.f("ix_rules_site_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_push_devices_user_id"), table_name="push_devices")
    op.drop_index(op.f("ix_push_devices_tenant_id"), table_name="push_devices")
    op.drop_table("push_devices")
    op.drop_index(op.f("ix_devices_tenant_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_site_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sites_tenant_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_table("tenants")
    op.drop_table("firmware_email_profiles")
    op.drop_index("ix_audit_tenant_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
